apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hallucinate-app.fullname" . }}-config
  labels:
    {{- include "hallucinate-app.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "ipfs_kit": {
        "role": "leecher",
        "enable_metadata_index": true
      },
      "observability": {
        "namespace": "ipfs_kit",
        "subsystem": "bridge",
        "logger_name": "ipfs_kit_bridge",
        "collect_system_metrics": {{ .Values.observability.systemMetricsEnabled }},
        "prometheus": {
          "enable_server": {{ .Values.observability.prometheusEnabled }},
          "port": {{ .Values.observability.prometheusPort }}
        },
        "system_metrics_interval": {{ .Values.observability.systemMetricsInterval }}
      }
    }