apiVersion: v1
kind: ConfigMap
metadata:
  name: hallucinate-app-config
  namespace: hallucinate-app
data:
  config.json: |-
    {
      "ipfs_kit": {
        "role": "leecher",
        "enable_metadata_index": true
      },
      "observability": {
        "namespace": "ipfs_kit",
        "subsystem": "bridge",
        "logger_name": "ipfs_kit_bridge",
        "collect_system_metrics": true,
        "prometheus": {
          "enable_server": true,
          "port": 9090
        },
        "system_metrics_interval": 15,
        "logging": {
          "level": "info",
          "json_format": true,
          "include_timestamp": true
        },
        "sdkGenerator": {
          "enabled": true,
          "namespace": "sdk_generator",
          "collectLanguageMetrics": true,
          "collectSizeMetrics": true
        }
      }
    }