apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hallucinate-app
  namespace: monitoring
  labels:
    app: hallucinate-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: hallucinate-app
  namespaceSelector:
    matchNames:
      - hallucinate-app
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
      path: /metrics